name: CufufyCore
version: '${project.version}' # Use version from pom.xml
main: com.cufufy.cufufyCore.CufufyCore
api-version: '1.21'
# ACF is now shaded, so it's not an external plugin dependency.
# If you had other actual plugin dependencies, they would go here.
# depend:
#  - OtherPlugin
authors: [YourName] # TODO: Replace with actual author
description: Core plugin for Cufufy project, providing shared functionalities.
website: https://www.example.com # TODO: Replace with actual website

# Default configuration values that will be saved to config.yml
# These are accessed via corePlugin.getConfig() after corePlugin.saveDefaultConfig()
# This is not a standard plugin.yml feature but a common way to bundle default configs.
# The actual config.yml will be created by Bukkit/Paper by copying these values.
# For this to work as a default config that saveDefaultConfig() uses,
# it should actually be a 'config.yml' file in resources.
# I will create a separate config.yml for this.
# For now, I will just note the structure here for clarity in the plan.
#
# config.yml structure would be:
# database:
#   enabled: true
#   type: "sqlite" # Options: sqlite, mysql, mariadb, postgresql
#   sqlite_file: "database.db" # Relative to plugin data folder
#   credentials: # For MySQL, MariaDB, PostgreSQL
#     host: "localhost"
#     port: 3306 # MySQL/MariaDB default, 5432 for PostgreSQL
#     database: "cufufy_core"
#     username: "user"
#     password: "password"
#     properties: "?autoReconnect=true&useSSL=false" # Optional JDBC connection string properties
#   pool_settings:
#     pool_name: "CufufyCore-HikariPool"
#     maximum_pool_size: 10
#     minimum_idle: 2
#     max_lifetime_ms: 1800000 # 30 minutes
#     connection_timeout_ms: 30000 # 30 seconds
#     idle_timeout_ms: 600000 # 10 minutes
#     properties: {} # E.g., cachePrepStmts: true, prepStmtCacheSize: 250
